### ISSUE TITLE
Alerts system

### ISSUE THREAD

**Issue by sallaben** [OpenSourceTagpro/web-client#7]
When the time is right, we need to implement alerts that appear as a floating translucent block on the top left of the web-client and fade within some amount of time.

This would be good for system messages/non chat information, or achievements -- "you just tagged your 100,000th player!", etc. 

This change would make the game more achievements-based too, and it'd be fun for players.

**Comment by samhh** [comment]
I think this belongs more-so in website repo?

**Comment by sallaben** [comment]
Wouldn't it be rendered in the client?

**Comment by samhh** [comment]
It would be counted/managed by the website backend, at least pre and post-game. Further, why limit its placement to the client's viewport when there is likely to be a wealth of space outside of it?

Regardless, this issue probably belongs in some sort of greater meta area (e.g. Discord discussion or meeting agenda) before being split into repo-specific sub-tasks.

**Comment by sallaben** [comment]
I think it's a little easier to focus on a single rectangle in your vision
(the viewport); I fear that blinking out-of-frame alerts would hurt
players' focus. It'd be something we have to experiment with.

How do you think it'd be implemented in the website?

**Comment by samhh** [comment]
That's fair.

Well, at a very high level the website backend has to store player stats in the database, else you won't have achievements/notifs/alerts that extend beyond one game.
